I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/scenes/default_scenes.rpy", line 31, in script call
    call input_player_name
  File "game/scripts/scenes/default_scenes.rpy", line 9, in script call
    call prologue
  File "game/scripts/scenes/default_scenes.rpy", line 66, in script
    Aphrodite "Oh...Arent you?"
Exception: Sayer 'Aphrodite' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/scenes/default_scenes.rpy", line 31, in script call
    call input_player_name
  File "game/scripts/scenes/default_scenes.rpy", line 9, in script call
    call prologue
  File "game/scripts/scenes/default_scenes.rpy", line 66, in script
    Aphrodite "Oh...Arent you?"
  File "C:\Users\Luan\Documents\Work\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Luan\Documents\Work\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Aphrodite' is not defined.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Koitatsu GUI 1.0.0
Wed Jan 11 10:06:10 2023
